import { StyleSheet } from "react-native";
import { Colors, Radius, Spacing, Typography } from "../constants/theme";

export const aiChatStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#000000",
  },
  headerGradientWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingBottom: 24, // Fades down smoothly below the actual header
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerIconContainer: {
    justifyContent: "center",
    alignItems: "center",
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(91,164,229,0.1)",
    borderWidth: 1,
    borderColor: "rgba(91,164,229,0.3)",
  },
  headerTitle: {
    color: Colors.textPrimary,
    fontSize: Typography.fontSizeLG,
    fontWeight: Typography.fontWeightBold,
    letterSpacing: 0.3,
  },
  closeBtn: {
    padding: 8,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  messageList: {
    padding: Spacing.md,
    paddingBottom: Spacing.xl,
  },
  bubble: {
    maxWidth: "85%",
    marginVertical: 4,
    borderRadius: Radius.lg,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#16283B",
    borderBottomRightRadius: 4,
  },
  aiBubble: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderBottomLeftRadius: 4,
    flexDirection: "row",
    gap: 10,
  },
  aiIconContainer: {
    marginTop: 2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(91,164,229,0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(91,164,229,0.3)",
  },
  bubbleText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: 0.3,
  },
  userText: {
    color: "#ffffffaa",
    fontWeight: "500",
  },
  aiText: {
    color: Colors.textPrimary,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.xl,
    paddingTop: 100,
    gap: 16,
  },
  sparkleContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(91, 165, 229, 0)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  emptyTitle: {
    fontSize: Typography.fontSizeXXL,
    fontWeight: Typography.fontWeightBold,
    color: Colors.textPrimary,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: Typography.fontSizeMD,
    color: Colors.textSecondary,
    textAlign: "center",
    lineHeight: 24,
  },
  quickPrompts: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: Spacing.lg,
    gap: 10,
    paddingBottom: Spacing.md,
    justifyContent: "center",
  },
  chip: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: Radius.full,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  chipPressed: {
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  chipText: {
    color: Colors.textPrimary,
    fontSize: Typography.fontSizeSM,
    fontWeight: "500",
  },

  // Custom Sleek Input Area Styles
  inputArea: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 12,
    alignItems: "center",
  },
  uploadBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(91,164,229,0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(91,164,229,0.3)",
  },
  inputWrapper: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    backgroundColor: "rgba(255,255,255,0.05)",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    paddingRight: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  glowLineContainer: {
    height: 18,
    width: 2,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  glowLine: {
    position: "absolute",
    width: 1.5,
    height: "100%",
    backgroundColor: "#86B5FF",
    borderRadius: 1,
    zIndex: 2,
  },
  glowLineBlur: {
    position: "absolute",
    width: 4,
    height: "120%",
    backgroundColor: "#5BA4E5",
    opacity: 0.6,
    borderRadius: 2,
    shadowColor: "#5BA4E5",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
    elevation: 4,
  },
  input: {
    flex: 1,
    color: "#E2E4E9",
    fontSize: 15,
    fontWeight: "400",
    height: "100%",
  },
});
